# Generated by Django 3.1.7 on 2021-02-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210224_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='days',
        ),
    ]
