# Generated by Django 3.1.7 on 2021-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_problem_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='waterAmount',
            field=models.TextField(max_length=250),
        ),
    ]
