# Generated by Django 3.1.7 on 2021-02-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210224_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='problems',
            field=models.ManyToManyField(to='main_app.Problem'),
        ),
    ]
