# Generated by Django 3.1.7 on 2021-02-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_plant_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='waterAmount',
            field=models.IntegerField(),
        ),
    ]
